### ISSUE TITLE
Make the Marketing Web Site Part of AP repositories

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/technical-steering-committee#28] opened 2021-03-16 23:22 UTC
The source code for the Marketing Site https://accordproject.org is not public. I recall somewhat that there are questions of copyright or property for some of the assets (logo? or maybe web site code and style?).

# Discussion 🗣

It would be good if the marketing site could be put in the Accord Project GitHub, with or without an Apache-2.0 license. I'm unclear on the ramifications.

## Context

A third party vendor was contracted by Clause Inc. to redesign the Accord Project marketing Web Site. I'm unclear on the terms of the contracts and ownership.

## Related Issues

- #6

**Comment by jeromesimeon** [comment] 2021-03-16 23:22
We may need more context and details from @Michael-Grover and/or @peterhunn

**Comment by martinhalford** [comment] 2021-04-29 12:02
From TSC Meeting 25-March 2021

```
- Michael provided context.
- WordPress site developed by design agency a number of years ago.
- Issue is that site is difficult to change. Only Clause have edit permission.
- Edits can only be made via WordPress CMS Login.
- Jerome - specific issue is that the web site is only AP asset not managed under AP GitHub. (NB: Code is on GitHub but in private Clause repo.)
- There is also a question on whether AP own IP assets in web site. 
- **ACTION** 
	- Michael to check on who owns assets.
- Once ownership is confirmed the relatively easy process to migrate code to AP GitHub repo.
```

**Comment by martinhalford** [comment] 2021-04-30 01:28
From TSC Meeting 29-April 2021.

- Peter mentioned there are a couple of minor issues to be cleared up on Clause side. 
- Specifically, items like copyright for fonts and some design elements of the site.
- Should be fine but will get an answer back within next week to 10 days.
- Once cleared, then transfer from Clause GitHub repo to AP GitHub repo relatively straight-forward.
- Jerome has created a target repo in AP GitHub and is ready to receive source code.
- Dan highlighted that the Accord Project web site does use a commercial WordPress plug-in at a cost of, circa, $30 per year to use.
- Therefore, AP web site won't be 100% open source but not a technical issue.
- **ACTION** 
	- Peter to chase legal clarifications and report accordingly.
- Once ownership is confirmed then relatively easy process to migrate code to AP GitHub repo.

**Comment by martinhalford** [comment] 2021-07-11 06:27
From TSC Meeting, 24 June 2021.
- No change since last meeting.
- On hold while Peter on leave.
- **ACTION** 
	- Peter to chase legal clarifications and report accordingly.
- Once ownership is confirmed then relatively easy process to migrate code to AP GitHub repo.

**Comment by martinhalford** [comment] 2021-09-30 07:47
From TSC Meeting, 26 Aug 2021.
- Have received clarification regarding ownership and now have all clear to migrate code to AP GitHub.
- **ACTION** 
	- Jerome to migrate code to AP GitHub repo.

**Comment by martinhalford** [comment] 2021-09-30 20:51
Pending.

**Comment by martinhalford** [comment] 2022-02-24 21:21
- New PR raised on new (private) accordproject.org repo - code for marketing site. Wordpress.
- Not all code inside template is open source therefore private repo. Can use proprietary code but cannot distribute it.
- PR to be merged and access rights to be setup - including Michael.

**Comment by martinhalford** [comment] 2022-03-31 20:12
Done.

**Closed by martinhalford** 2022-03-31 20:12 UTC
Labels: Type: Discussion 🗣, Type: Need Investigation 🔬, Docket: Queue 📥
